### PR TITLE
Update GNOME Sdk to 43

### PR DESCRIPTION
**Pull request by starnight**

### CODE REVIEW

**Comment by starnight** [comment]
Blocked on https://github.com/flathub/flatpak-builder-lint/pull/95

**Comment by starnight** [comment]
Bot start test

**Comment by starnight** [comment]
Blocked on https://github.com/flathub/org.flatpak.Builder/pull/129

**Review by wjt — COMMENTED** [review]
It doesn't have to be blocked. We can just remove the offending `test-commands`, which aren't being used.

**Comment by cassidyjames** [comment]
For what it's worth, when testing the built Flatpak on Fedora Silverblue:

```
$ flatpak run com.hack_computer.Clubhouse 
Gtk-Message: 21:05:27.570: Failed to load module "/app/clippy/lib/libclippy-module.so"
Traceback (most recent call last):
  File "/app/bin/eos-clubhouse", line 62, in <module>
    _run_clubhouse()
  File "/app/bin/eos-clubhouse", line 36, in _run_clubhouse
    from eosclubhouse.clubhouse import ClubhouseApplication
  File "/app/lib/python3.10/site-packages/eosclubhouse/clubhouse.py", line 41, in <module>
  File "/app/lib/python3.10/site-packages/eosclubhouse/libquest.py", line 24, in <module>
```

**Comment by starnight** [comment]
Ya ~  It is blocked on https://github.com/flathub/com.hack_computer.Clippy.Extension/pull/2

**Pull request merged**
